name: Next.js Build Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'application/**'
      - '.github/workflows/nextjs-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Install dependencies
        working-directory: ./application
        run: pnpm install
        
      - name: Run lint
        working-directory: ./application
        run: pnpm run lint
        
      - name: Build Next.js application
        working-directory: ./application
        run: pnpm run build